name: 'Setup Build Environment'
description: 'Installs all required dependencies for Linux and Windows runners.'

runs:
  using: "composite"

  steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: | 
          8.0.x
          9.0.x
          10.0.x

    - name: Run Linux setup script
      if: runner.os == 'Linux'
      run: |
        chmod +x ${{ github.action_path }}/../../scripts/install_deps.sh
        sudo ${{ github.action_path }}/../../scripts/install_deps.sh
      shell: bash

    - name: Run Windows setup script
      if: runner.os == 'Windows'
      run: ${{ github.action_path }}/../../scripts/install_deps.ps1
      shell: pwsh