name: 'Setup Build Environment'
description: 'Installs all required dependencies for Linux and Windows runners.'

inputs:
  install-build-tools:
    description: 'Whether to install Linux build tools like flatpak and AppImageTool.'
    required: true

runs:
  using: "composite"

  steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: | 
          8.0.x
          9.0.x
          10.0.x

    - name: Setup Bun
      if: runner.os == 'Linux'
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Run Linux setup script
      if: runner.os == 'Linux'
      run: |
        chmod +x ${{ github.action_path }}/../../scripts/install_deps.sh
        sudo INSTALL_BUILD_TOOLS="${{ inputs.install-build-tools }}" ${{ github.action_path }}/../../scripts/install_deps.sh
      shell: bash

    - name: Run Windows setup script
      if: runner.os == 'Windows'
      run: ${{ github.action_path }}/../../scripts/install_deps.ps1
      shell: pwsh