name: 'Cached LFS Checkout'
description: 'Checkout code from GitHub using LFS in tandem with caching to reduce bandwidth usage.'

runs:
  using: "composite"

  steps:
    - name: Generate LFS hash key
      shell: bash
      run: git lfs ls-files --long > .lfs-files.txt || true
    - name: Restore LFS cache
      id: lfs-cache
      uses: actions/cache@v4
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-files.txt') }}
        restore-keys: |
          ${{ runner.os }}-lfs-
    - name: Pull LFS files
      shell: bash
      run: git lfs pull