//HintName: ExportRegistrar.g.cs
// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using AvaloniaXKCD.Exports;

namespace AvaloniaXKCD.Generated
{
    internal static class ExportRegistrar
    {
        [ModuleInitializer]
        internal static void RegisterExports()
        {
            // Register single implementation for TestNamespace.IService
            Debug.WriteLine("Registering export: TestNamespace.IService -> TestNamespace.ServiceImpl");
            ExportContainer.Add<TestNamespace.IService, TestNamespace.ServiceImpl>();
        }
    }
}