//HintName: ExportRegistrar.g.cs
// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using AvaloniaXKCD.Exports;

namespace AvaloniaXKCD.Generated
{
    internal static class ExportRegistrar
    {
        [ModuleInitializer]
        internal static void RegisterExports()
        {
            // Register implementation for TestNamespace.IService
            Debug.WriteLine("Registering export with factory: TestNamespace.IService -> TestNamespace.MyService");
            ExportContainer.Add<TestNamespace.IService, TestNamespace.MyService>(() => new TestNamespace.MyService(new TestNamespace.Repo(), new TestNamespace.Logger()));
        }
    }
}