//HintName: ExportRegistrar.g.cs
// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using AvaloniaXKCD.Exports;

namespace AvaloniaXKCD.Generated
{
    internal static class ExportRegistrar
    {
        [ModuleInitializer]
        internal static void RegisterExports()
        {
            // Register implementation for TestNamespace.IService1
            Debug.WriteLine("Registering export: TestNamespace.IService1 -> TestNamespace.MultiService");
            ExportContainer.Add<TestNamespace.IService1, TestNamespace.MultiService>();
            // Register implementation for TestNamespace.IService2
            Debug.WriteLine("Registering export: TestNamespace.IService2 -> TestNamespace.MultiService");
            ExportContainer.Add<TestNamespace.IService2, TestNamespace.MultiService>();
        }
    }
}