//HintName: ExportRegistrar.g.cs
// <auto-generated/>
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using AvaloniaXKCD.Exports;

namespace AvaloniaXKCD.Generated
{
    internal static class ExportRegistrar
    {
        [ModuleInitializer]
        internal static void RegisterExports()
        {
            // Register 2 implementations for TestNamespace.IService (multi-registration)
            Debug.WriteLine("Registering multi-export: TestNamespace.IService -> TestNamespace.ServiceImpl1");
            ExportContainer.AddMulti<TestNamespace.IService, TestNamespace.ServiceImpl1>();
            Debug.WriteLine("Registering multi-export: TestNamespace.IService -> TestNamespace.ServiceImpl2");
            ExportContainer.AddMulti<TestNamespace.IService, TestNamespace.ServiceImpl2>();
        }
    }
}