//HintName: ServiceProvider.g.cs
// <auto-generated/>
using System;
using Microsoft.Extensions.DependencyInjection;

// This file is generated by the ServiceProviderGenerator. Do not edit!!
namespace TestNamespace
{
    internal partial class ServiceProvider
    {
#nullable enable
        private IServiceProvider? _services;
#nullable disable
        public partial IServiceProvider Services
        {
            get
            {
                if (_services == null)
                {
                    throw new InvalidOperationException("Services have not been configured.");
                }
                return _services!;
            }
        }

        public partial void ConfigureServices(ServiceCollection services)
        {
            if (_services != null)
                throw new InvalidOperationException("Services have already been configured.");

            services.AddSingleton<TestNamespace.TestService>();

            _services = services.BuildServiceProvider();
        }
    }
}