//HintName: ViewLocator.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;

// This file is generated by the ViewLocatorGenerator. Do not edit!!
namespace TestNamespace
{
    internal partial class ViewLocator
    {
        private partial Dictionary<Type, Type> CreateViewModelViewMap()
        {
            return new()
            {
                { typeof(TestNamespace.MainViewModel), typeof(TestNamespace.MainView) }
            };
        }
    }
}