//HintName: ViewLocator.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;

// This file is generated by the ViewLocatorGenerator. Do not edit!!
namespace Test
{
    internal partial class ViewLocator
    {
        private partial Dictionary<Type, Type> CreateViewModelViewMap()
        {
            return new()
            {
                { typeof(Test.UserViewModel), typeof(Test.UserView) }
            };
        }
    }
}