global using AvaloniaXKCD.Tests.Orchestration;
global using AvaloniaXKCD.Tests.TestBases;
global using AvaloniaXKCD.Exports;
global using static AvaloniaXKCD.Tests.VerifyPlugins.VerifySourceGeneratorsPlugin;
global using static AvaloniaXKCD.Tests.VerifyPlugins.VerifyAssertionsPlugin;
global using static AvaloniaXKCD.Tests.VerifyPlugins.VerifyHeadlessAvaloniaPlugin;
global using AvaloniaXKCD.Tests.VerifyPlugins;
global using XKCDCore;

global using AvaloniaXKCD.Generators;
global using Shouldly;
global using Microsoft.Playwright;
global using TUnit.Playwright;
global using System.Diagnostics;
global using System.Text.RegularExpressions;
global using TUnit.Core.Interfaces;
global using Avalonia.Headless;
global using Avalonia.Threading;
global using AvaloniaXKCD.ViewModels;
global using AvaloniaXKCD.Views;
global using TUnit.Core.Executors;
global using Microsoft.CodeAnalysis;
global using System.Net;